# https://jupyterbook.org/en/stable/customize/config.html
name: quanttide-tutorial-of-digital-economics
title: 量潮数字经济学教程
author: 量潮科技
description: 面向经管专业和互联网行业的数字经济学入门和精进教程
# Jupyter Book Config
only_build_toc_files: true